library_django/catalog/urls.py
from django.urls import path, re_path
from catalog.views import (index, AuthorListView, AuthorDetailView, BookListView, BookDetailView,
                           BookInstanceDetail, reserve_book, owned_books)

urlpatterns = [
    path('', index, name='index'),
    path('authors/', AuthorListView.as_view(), name='authors'),
    path('books/', BookListView.as_view(), name='books'),
    re_path(r'^authors/(?P<pk>\d+)/$', AuthorDetailView.as_view(), name='author-detail'),
    re_path(r'^books/(?P<pk>\d+)/$', BookDetailView.as_view(), name='book-detail'),
    re_path(r'^books_instance/(?P<pk>\d+)/$', BookInstanceDetail.as_view(), name='book_instance-detail'),
    path('reserve-book/<int:book_instance_id>/', reserve_book, name='reserve_book'),
    path('owned-books/', owned_books, name='owned_books'),
]

library_django/library_django/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls')),
    path('', include('users.urls'))
]

library_django/users/urls.py
from django.urls import path
from users import views


urlpatterns = [
    path('signup/', views.signup_user, name='signup_user'),
    path('login/', views.login_user, name='login_user'),
    path('logout/', views.logout_user, name='logout_user')
]

library_django/catalog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from django.utils import timezone
from datetime import timedelta


class Genre(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Country(models.Model):
    name = models.CharField(max_length=100)

    class Meta:
        verbose_name_plural = 'Countries'

    def __str__(self):
        return self.name


class Language(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Author(models.Model):
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100, null=True, blank=True)
    pseudonym = models.CharField(max_length=100, null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_death = models.DateField(null=True, blank=True)
    country = models.ForeignKey(Country, on_delete=models.CASCADE)
    
    def __str__(self):
        return (f"{self.first_name}"
                f"{self.last_name if self.last_name else ''}"
                f"{self.pseudonym if self.pseudonym else ''}")

    def get_absolute_url(self):
        return reverse('author-detail', args=[self.pk])


class Book(models.Model):
    title = models.CharField(max_length=255)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    genre = models.ManyToManyField(Genre)

    def display_genre(self):
        return ', '.join([genre.name for genre in self.genre.all()])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('book-detail', args=[self.pk])


class BookInstance(models.Model):
    STATUSES = (
        ('Available', 'Available'),
        ('On Loan', 'On Loan'),
        ('Lost', 'Lost'),
        ('On Service', 'On Service')
    )
    book = models.ForeignKey(Book, on_delete=models.CASCADE)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    language = models.ForeignKey(Language, on_delete=models.CASCADE)
    status = models.CharField(choices=STATUSES, max_length=50, default='Available')
    due_back = models.DateField(null=True, blank=True)
    isbn = models.CharField(max_length=13)

    def __str__(self):
        return f"{self.book.title} {self.isbn}"

    def get_absolute_url(self):
        return reverse('book_instance-detail', args=[self.pk])

library_django/users/models.py
from django.db import models

# Create your models here.

library_django/catalog/forms.py
from django import forms
from catalog.models import BookInstance


class BookReservationForm(forms.ModelForm):
    class Meta:
        model = BookInstance
        fields = ['book', 'due_book']

    def save(self, user, commit=True):
        book_instance = super().save(commit=False)
        book_instance.borrower = user
        book_instance.status = 'On Loan'
        if commit:
            book_instance.save()
        return book_instance

library_django/catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from catalog.models import Book, Author, BookInstance, Genre
from django.views.generic import ListView, DetailView
from django.utils import timezone
from datetime import timedelta
from django.contrib.auth.decorators import login_required


def index(request):
    num_books = Book.objects.all().count()
    num_authors = Author.objects.all().count()
    num_book_instances = BookInstance.objects.all().count()
    num_instances_available = BookInstance.objects.filter(status__exact='Available').count()

    return render(request, 'index.html', {
        "num_books": num_books,
        "num_author": num_authors,
        "num_book_instances": num_book_instances,
        "num_instances_available": num_instances_available
    })


class AuthorListView(ListView):
    model = Author
    template_name = 'authors_list.html'
    context_object_name = 'authors_list'


class AuthorDetailView(DetailView):
    model = Author
    template_name = 'author_detail.html'


class BookListView(ListView):
    model = Book
    template_name = 'books_list.html'
    context_object_name = 'books_list'


class BookDetailView(DetailView):
    model = Book
    template_name = 'book_detail.html'


class BookInstanceDetail(DetailView):
    model = BookInstance
    template_name = 'book_instance_detail.html'


@login_required
def owned_books(request):
    user = request.user
    book_instance = BookInstance.objects.filter(borrower=user)
    context = {
        'book_instance': book_instance
    }

    return render(request, 'reserved_detail.html', context)


@login_required
def reserve_book(request, book_instance_id):
    has_overdue_books = BookInstance.objects.filter(borrower=request.user, status='On Loan',
                                                    due_back__lt=timezone.now().date()).exists()
    if has_overdue_books:
        return render(request, 'reserved_detail.html',
                      {'message': 'You have expired books. It is not possible to book a new book.'})
    book_instance = get_object_or_404(BookInstance, id=book_instance_id)
    book_instance.status = 'On Loan'
    book_instance.due_back = timezone.now().date() + timedelta(weeks=2)
    book_instance.borrower = request.user
    book_instance.save()
    return render(request, 'reserved_book.html', {'book_instance': book_instance})

library_django/users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.db import IntegrityError
from django.contrib.auth import login, logout, authenticate


def signup_user(request):
    if request.method == 'GET':
        return render(request, 'signup_user.html', {'form': UserCreationForm()})
    else:
        if request.POST['password1'] == request.POST['password2']:
            try:
                user = User.objects.create_user(request.POST['username'], password=request.POST['password1'])
                user.save()
                login(request, user)
                return redirect('index')
            except IntegrityError:
                return render(request, 'signup_user.html',
                              {'form': UserCreationForm(), 'error': 'That username has already been taken.'})
        else:
            return render(request, 'signup_user.html', {'form': UserCreationForm(), 'error': 'Passwords did not match'})


def login_user(request):
    if request.method == 'GET':
        return render(request, 'login_user.html', {'form': AuthenticationForm()})
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'login_user.html', {'form': AuthenticationForm(), 'error': 'Username and password did not match'})
        else:
            login(request, user)
            return redirect('index')


def logout_user(request):
    if request.method == 'POST':
        logout(request)
        return redirect('login_user')

library_django/catalog/templates/author_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Author</h1>
    <h2>Real name: {{author.first_name }} - {{ author.last_name }}</h2>
    <h2>Pseudonym: {{ author.pseudonym }}</h2>
    <h2>Country: {{ author.country.name }}</h2>
    {% if author.date_of_death %}
        <h2>Dates: {{ author.date_of_birth }} - {{ author.date_of_death }}</h2>
    {% else %}
        <h2>Dates: {{author.date_of_birth }} - Unknown </h2>

    {% endif %}

{% endblock %}

library_django/catalog/templates/authors_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Authors List:</h1>
  {% for author in authors_list %}
    <h3><a href="{{ author.get_absolute_url }}">{{ author }}</a></h3>

  {% endfor %}

{% endblock %}

library_django/catalog/templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

</head>
<body>


<nav class="navbar navbar-expand-md navbar-light bg-warning">
<div class="container">
    <a class="navbar-brand" href="{% url 'index' %}">
        <span>Home</span>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
    {% if user.is_authenticated %}
        <ul class="navbar-nav mr-auto">
                    <a class="nav-link" href="{% url 'authors' %}">Authors</a>
                <li class="nav-item {{ completed }}">
                    <a class="nav-link" href="{% url 'books' %}">Books</a>
                </li>
                <li class="nav-item {{ create }}">
                    <a class="nav-link" href="{% url 'owned_books' %}">Reserved</a>
                </li>

        </ul>
    {% endif %}
    <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'login_user' %}" onclick="$('#signOutBtn').click()" class="nav-link">Logout</a>
                    <form style='display: none;' method="POST" action="{% url 'logout_user' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Logout</button>
                    </form>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup_user' %}">Sign Up</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login_user' %}">Login</a>
                </li>
            {% endif %}
        </ul>
    </div>
</div>
</nav>

<div class="container">
{% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

library_django/catalog/templates/book_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1>Book</h1>
    <h2>Title: {{book.title }}</h2>
    <h2>Author: {{ book.author.first_name}} {{book.author.last_name}} - {{book.author.pseudonym }}</h2>
    <h2>Genre: </h2>
    {% for genre in book.genre.all %}
        <h2> {{ genre.name }} {% if not forloop.last %}, {% endif %}</h2>

    {% endfor %}

    <h1 class="card-text">Available Copies: </h1>
    {% for book_instance in book.bookinstance_set.all %}
    {% if book_instance.status == 'Available' %}
        <h4 class="card-text">
            <a href="{{ book_instance.get_absolute_url }}">
                {{ book_instance.isbn}} {{ book_instance.language.name }}
            </a>
        </h4>
    {% endif %}
{% endfor %}

{% endblock %}

library_django/catalog/templates/book_instance_detail.html
{% extends 'base.html' %}

{% block content %}
    <h1><a href="{{ bookinstance.book.get_absolute_url }}">{{ bookinstance.book }}</a></h1>
    <h2>ISBN: {{ bookinstance.isbn }}</h2>
    <h2>Language: {{ bookinstance.language.name }}</h2>
    <h2>Status: {{ bookinstance.status }}</h2>

   {% if bookinstance.status == 'Available' %}
    <form action="{% url 'reserve_book' bookinstance.id %}" method="post">
        {% csrf_token %}
        <button type="submit">Reserve</button>
    </form>
{% endif %}
{% endblock %}

library_django/catalog/templates/books_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Books List:</h1>

  {% for book in books_list %}
    <h3><a href="{{ book.get_absolute_url }}">{{ book }}</a></h3>

  {% endfor %}



{% endblock %}

library_django/catalog/templates/index.html
{% extends 'base.html' %}

{% block content %}
    <h1>Local Library</h1>

    <ul>
        <li>Books: {{ num_books }}</li>
        <li>Authors: {{ num_authors }}</li>
        <li>Book Copies: {{ num_book_instances }}</li>
        <li>Book Copies Available now: {{ num_instances_available }}</li>
    </ul>

{% endblock %}

library_django/catalog/templates/reserved_book.html
{% extends 'base.html' %}

{% block content %}
    <h1>Book</h1>
    <h2>Title: {{book_instance.book.title }}</h2>
    <h2>Author: {{ book_instance.book.author.first_name}} {{book_instance.book.author.last_name}} - {{book_instance.book.author.pseudonym }}</h2>
    <h2>Genre: </h2>
    {% for genre in book_instance.book.genre.all %}
        <h2> {{ genre.name }} {% if not forloop.last %}, {% endif %}</h2>
    {% endfor %}
    <h2>Borrower: {{ book_instance.borrower }} </h2>


{% endblock %}

library_django/catalog/templates/reserved_detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>Books Owned by {{ user.username }}</h1>
{{ message }}
  {% if book_instance %}
    <ul>
      {% for book in book_instance %}
        <li>Title: {{ book.book.title }}</li>
        <li>ISBN: {{ book.isbn }}</li>
        <li>Due Back: {{ book.due_back }}</li>
      {% endfor %}
    </ul>
  {% else %}
    <p>No books owned.</p>
  {% endif %}
{% endblock %}

library_django/users/templates/login_user.html
{% extends "base.html" %}

{% block content %}
<title>Login</title>

<style>
    body {
        background-color: white;
    }
    .form-wrapper {
        border: 2px solid #ccc;
        padding: 20px;
        border-radius: 10px;
        background-color: white;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }
    .btn-primary:hover {
        opacity: 0.6;
    }
    .login-title {
        font-weight: bold;
    }
</style>
<div class="d-flex justify-content-center mt-5">
    <div class="col-md-5">
        <h2 class="text-center login-title">Login</h2>
        <div class="form-wrapper">
            {% if error %}
                <div class="alert alert-danger" role="alert">
                    {{ error }}
                </div>
            {% endif %}
            <form method="POST">
                {% csrf_token %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" name="username" class="form-control" id="username">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" name="password" class="form-control" id="password">
                </div>
                <div class="text-center">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </form>
            <hr>
            <div class="text-center">
                Don't have an account yet? <a href="{% url 'signup_user' %}">Sign Up</a>
            </div>
        </div>
    </div>
</div>

{% endblock %}

library_django/users/templates/signup_user.html
{% extends "base.html" %}

{% block content %}
<title>Sign Up</title>
<style>
    body {
        background-color: white;
    }
    .form-wrapper {
        border: 2px solid #ccc;
        padding: 20px;
        border-radius: 10px;
        background-color: white;
        box-shadow: 0 0 10px rgba(0, 0, 0, 0.1), 0 2px 4px rgba(0, 0, 0, 0.1);
    }
    .btn-primary {
        background-color: #007bff;
        border-color: #007bff;
    }
    .btn-primary:hover {
        opacity: 0.6;
    }
    .registration-title {
        font-weight: bold;
    }


</style>
<div class="row justify-content-center mt-5">
    <div class="col-md-5">
        <h2 class="text-center registration-title">Sign Up</h2>
    </div>
</div>
<div class="row justify-content-center mt-5">
    <div class="col-md-5 form-wrapper">
        {% if error %}
            <div class="alert alert-danger" role="alert">
                {{ error }}
            </div>
        {% endif %}
        <form method="POST">
            {% csrf_token %}
            <div class="form-group">
                <label for="username">Username</label>
                <input type="text" name="username" class="form-control" id="username" aria-describedby="usernameHelp">
                <small id="usernameHelp" class="form-text text-muted">Your username must be unique. We will inform you if someone has already used it.</small>
            </div>
            <div class="form-group">
                <label for="password1">Password</label>
                <input type="password" name="password1" class="form-control" id="password1">
            </div>
            <div class="form-group">
                <label for="password2">Confirm Password</label>
                <input type="password" name="password2" class="form-control" id="password2">
            </div>
            <div class="row justify-content-center mt-5">
                <div class="col-md-5 text-center">
                    <button type="submit" class="btn btn-primary">Sign Up</button>
                </div>
            </div>
        </form>
        <hr>
        <div class="text-center">
            Already have an account? <a href="{% url 'login_user' %}">Login to your account</a>
        </div>
    </div>
</div>

{% endblock %}